### ISSUE TITLE
How to remove/unload the editor?

### ISSUE THREAD

**Issue by ahmadazizi** [toopay/bootstrap-markdown#277] opened 2017-02-26 15:01 UTC
In some scenarios it would be required to remove the editor after it has been loaded, for e.g. to switch editors.
I fount no methods to remove or unload this editor.
in some editors there is options for this.
How do you remove / unload bootstrap-markdown that has loaded on a textarea?

**Comment by toopay** [comment] 2017-07-18 09:34
Duplicate of #282

**Closed by toopay** 2017-07-18 09:34 UTC
