### ISSUE TITLE
what about bs4?

### ISSUE THREAD

**Issue by paulprok** [toopay/bootstrap-markdown#311] opened 2017-10-14 17:39 UTC
is it planned to support bs4 in close time?
thanx

**Comment by acrobat** [comment] 2017-10-14 20:52
I think the first step will be by just testing the current code with BS4 and report back the issues with BS4 compatibility

**Comment by Ionaru** [comment] 2017-11-30 09:55
After a quick test it looks like a few things are broken with Bootstrap 4:
* Buttons have no content and are very tiny
* Rendered markdown is not working

![screenshot_20171130_105256](https://user-images.githubusercontent.com/3472373/33424661-c1c47650-d5bc-11e7-90e9-bee626839f3a.png)

Tested with `bootstrap: 4.0.0-beta.2` and `bootstrap-markdown: 2.10.0`

**Comment by royduin** [comment] 2018-02-02 09:44
In Bootstrap 4 doesn't include any font library anymore like Glyphicons in Bootstrap 3. Just use Font Awesome with the `iconlibrary` option.

**Comment by althaus** [comment] 2018-02-15 15:20
Those are the issues I encountered so far besides missing icons:

* `btn-secondary` instead of `btn-default`
* `hidden` attribute instead of class
* `btn-group` has no more margin, add for example `mr-2` 

I simply added an `onShow` callback as an intermediate fix:

    const fixEditor = function(e) {
        const $toolbar = e.$editor.find('.btn-toolbar');

        $toolbar.find('.btn-default').removeClass('btn-default').addClass('btn-secondary');
        $toolbar.find('.hidden').removeClass('hidden').prop('hidden', true);
        $toolbar.find('.btn-group').not(':last-child').addClass('mr-2');
    };

**Comment by NicolasCARPi** [comment] 2018-03-30 13:14
This issue is a duplicate of #213.

**Closed** 2018-03-30 13:57 UTC
